/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowReportingWorksRouteImport } from './routes/how-reporting-works'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ModerationPolicyRouteImport } from './routes/moderation-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DataAddgroupRouteImport } from './routes/data.addgroup'
import { Route as GroupAddgroupRouteImport } from './routes/group.addgroup'
import { Route as GroupFindRouteImport } from './routes/group.find'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesHowToAvoidWhatsappScamsRouteImport } from './routes/guides.how-to-avoid-whatsapp-scams'
import { Route as GuidesHowToJoinWhatsappGroupsSafelyRouteImport } from './routes/guides.how-to-join-whatsapp-groups-safely'
import { Route as GuidesWhatsappCommunityVsGroupRouteImport } from './routes/guides.whatsapp-community-vs-group'
import { Route as GuidesWhatsappGroupAdminGuidelinesRouteImport } from './routes/guides.whatsapp-group-admin-guidelines'
import { Route as GuidesWhatsappGroupsCountryJoiningGuideRouteImport } from './routes/guides.whatsapp-groups-country-joining-guide'
import { Route as CategorySlugGroupRouteImport } from './routes/category.$slug_.$group'
import { Route as GroupCategorySlugRouteImport } from './routes/group.category.$slug'
import { Route as GroupCountrySlugRouteImport } from './routes/group.country.$slug'
import { Route as GroupLanguageSlugRouteImport } from './routes/group.language.$slug'
import { Route as GroupInviteWhatsappCodeRouteImport } from './routes/group.invite.whatsapp.$code'
import { Route as GroupJoinWhatsappCodeRouteImport } from './routes/group.join.whatsapp.$code'
import { Route as GroupRulesWhatsappCodeRouteImport } from './routes/group.rules.whatsapp.$code'
import { Route as GroupInviteWhatsappCodeIndexRouteImport } from './routes/group.invite.whatsapp.$code.index'
import { Route as GroupInviteWhatsappCodeJoinRouteImport } from './routes/group.invite.whatsapp.$code.join'
import { Route as GroupInviteWhatsappCodeJoinNowRouteImport } from './routes/group.invite.whatsapp.$code.join-now'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowReportingWorksRoute = HowReportingWorksRouteImport.update({
  id: '/how-reporting-works',
  path: '/how-reporting-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationPolicyRoute = ModerationPolicyRouteImport.update({
  id: '/moderation-policy',
  path: '/moderation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAddgroupRoute = DataAddgroupRouteImport.update({
  id: '/data/addgroup',
  path: '/data/addgroup',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupAddgroupRoute = GroupAddgroupRouteImport.update({
  id: '/group/addgroup',
  path: '/group/addgroup',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupFindRoute = GroupFindRouteImport.update({
  id: '/group/find',
  path: '/group/find',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHowToAvoidWhatsappScamsRoute =
  GuidesHowToAvoidWhatsappScamsRouteImport.update({
    id: '/guides/how-to-avoid-whatsapp-scams',
    path: '/guides/how-to-avoid-whatsapp-scams',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToJoinWhatsappGroupsSafelyRoute =
  GuidesHowToJoinWhatsappGroupsSafelyRouteImport.update({
    id: '/guides/how-to-join-whatsapp-groups-safely',
    path: '/guides/how-to-join-whatsapp-groups-safely',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesWhatsappCommunityVsGroupRoute =
  GuidesWhatsappCommunityVsGroupRouteImport.update({
    id: '/guides/whatsapp-community-vs-group',
    path: '/guides/whatsapp-community-vs-group',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesWhatsappGroupAdminGuidelinesRoute =
  GuidesWhatsappGroupAdminGuidelinesRouteImport.update({
    id: '/guides/whatsapp-group-admin-guidelines',
    path: '/guides/whatsapp-group-admin-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesWhatsappGroupsCountryJoiningGuideRoute =
  GuidesWhatsappGroupsCountryJoiningGuideRouteImport.update({
    id: '/guides/whatsapp-groups-country-joining-guide',
    path: '/guides/whatsapp-groups-country-joining-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategorySlugGroupRoute = CategorySlugGroupRouteImport.update({
  id: '/category/$slug_/$group',
  path: '/category/$slug/$group',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCategorySlugRoute = GroupCategorySlugRouteImport.update({
  id: '/group/category/$slug',
  path: '/group/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCountrySlugRoute = GroupCountrySlugRouteImport.update({
  id: '/group/country/$slug',
  path: '/group/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupLanguageSlugRoute = GroupLanguageSlugRouteImport.update({
  id: '/group/language/$slug',
  path: '/group/language/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupInviteWhatsappCodeRoute = GroupInviteWhatsappCodeRouteImport.update({
  id: '/group/invite/whatsapp/$code',
  path: '/group/invite/whatsapp/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupJoinWhatsappCodeRoute = GroupJoinWhatsappCodeRouteImport.update({
  id: '/group/join/whatsapp/$code',
  path: '/group/join/whatsapp/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRulesWhatsappCodeRoute = GroupRulesWhatsappCodeRouteImport.update({
  id: '/group/rules/whatsapp/$code',
  path: '/group/rules/whatsapp/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupInviteWhatsappCodeIndexRoute =
  GroupInviteWhatsappCodeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GroupInviteWhatsappCodeRoute,
  } as any)
const GroupInviteWhatsappCodeJoinRoute =
  GroupInviteWhatsappCodeJoinRouteImport.update({
    id: '/join',
    path: '/join',
    getParentRoute: () => GroupInviteWhatsappCodeRoute,
  } as any)
const GroupInviteWhatsappCodeJoinNowRoute =
  GroupInviteWhatsappCodeJoinNowRouteImport.update({
    id: '/join-now',
    path: '/join-now',
    getParentRoute: () => GroupInviteWhatsappCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/how-reporting-works': typeof HowReportingWorksRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/moderation-policy': typeof ModerationPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/data/addgroup': typeof DataAddgroupRoute
  '/group/addgroup': typeof GroupAddgroupRoute
  '/group/find': typeof GroupFindRoute
  '/guides/how-to-avoid-whatsapp-scams': typeof GuidesHowToAvoidWhatsappScamsRoute
  '/guides/how-to-join-whatsapp-groups-safely': typeof GuidesHowToJoinWhatsappGroupsSafelyRoute
  '/guides/whatsapp-community-vs-group': typeof GuidesWhatsappCommunityVsGroupRoute
  '/guides/whatsapp-group-admin-guidelines': typeof GuidesWhatsappGroupAdminGuidelinesRoute
  '/guides/whatsapp-groups-country-joining-guide': typeof GuidesWhatsappGroupsCountryJoiningGuideRoute
  '/guides/': typeof GuidesIndexRoute
  '/category/$slug/$group': typeof CategorySlugGroupRoute
  '/group/category/$slug': typeof GroupCategorySlugRoute
  '/group/country/$slug': typeof GroupCountrySlugRoute
  '/group/language/$slug': typeof GroupLanguageSlugRoute
  '/group/invite/whatsapp/$code': typeof GroupInviteWhatsappCodeRouteWithChildren
  '/group/join/whatsapp/$code': typeof GroupJoinWhatsappCodeRoute
  '/group/rules/whatsapp/$code': typeof GroupRulesWhatsappCodeRoute
  '/group/invite/whatsapp/$code/join': typeof GroupInviteWhatsappCodeJoinRoute
  '/group/invite/whatsapp/$code/join-now': typeof GroupInviteWhatsappCodeJoinNowRoute
  '/group/invite/whatsapp/$code/': typeof GroupInviteWhatsappCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/how-reporting-works': typeof HowReportingWorksRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/moderation-policy': typeof ModerationPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/data/addgroup': typeof DataAddgroupRoute
  '/group/addgroup': typeof GroupAddgroupRoute
  '/group/find': typeof GroupFindRoute
  '/guides/how-to-avoid-whatsapp-scams': typeof GuidesHowToAvoidWhatsappScamsRoute
  '/guides/how-to-join-whatsapp-groups-safely': typeof GuidesHowToJoinWhatsappGroupsSafelyRoute
  '/guides/whatsapp-community-vs-group': typeof GuidesWhatsappCommunityVsGroupRoute
  '/guides/whatsapp-group-admin-guidelines': typeof GuidesWhatsappGroupAdminGuidelinesRoute
  '/guides/whatsapp-groups-country-joining-guide': typeof GuidesWhatsappGroupsCountryJoiningGuideRoute
  '/guides': typeof GuidesIndexRoute
  '/category/$slug/$group': typeof CategorySlugGroupRoute
  '/group/category/$slug': typeof GroupCategorySlugRoute
  '/group/country/$slug': typeof GroupCountrySlugRoute
  '/group/language/$slug': typeof GroupLanguageSlugRoute
  '/group/join/whatsapp/$code': typeof GroupJoinWhatsappCodeRoute
  '/group/rules/whatsapp/$code': typeof GroupRulesWhatsappCodeRoute
  '/group/invite/whatsapp/$code/join': typeof GroupInviteWhatsappCodeJoinRoute
  '/group/invite/whatsapp/$code/join-now': typeof GroupInviteWhatsappCodeJoinNowRoute
  '/group/invite/whatsapp/$code': typeof GroupInviteWhatsappCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/how-reporting-works': typeof HowReportingWorksRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/moderation-policy': typeof ModerationPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/data/addgroup': typeof DataAddgroupRoute
  '/group/addgroup': typeof GroupAddgroupRoute
  '/group/find': typeof GroupFindRoute
  '/guides/how-to-avoid-whatsapp-scams': typeof GuidesHowToAvoidWhatsappScamsRoute
  '/guides/how-to-join-whatsapp-groups-safely': typeof GuidesHowToJoinWhatsappGroupsSafelyRoute
  '/guides/whatsapp-community-vs-group': typeof GuidesWhatsappCommunityVsGroupRoute
  '/guides/whatsapp-group-admin-guidelines': typeof GuidesWhatsappGroupAdminGuidelinesRoute
  '/guides/whatsapp-groups-country-joining-guide': typeof GuidesWhatsappGroupsCountryJoiningGuideRoute
  '/guides/': typeof GuidesIndexRoute
  '/category/$slug_/$group': typeof CategorySlugGroupRoute
  '/group/category/$slug': typeof GroupCategorySlugRoute
  '/group/country/$slug': typeof GroupCountrySlugRoute
  '/group/language/$slug': typeof GroupLanguageSlugRoute
  '/group/invite/whatsapp/$code': typeof GroupInviteWhatsappCodeRouteWithChildren
  '/group/join/whatsapp/$code': typeof GroupJoinWhatsappCodeRoute
  '/group/rules/whatsapp/$code': typeof GroupRulesWhatsappCodeRoute
  '/group/invite/whatsapp/$code/join': typeof GroupInviteWhatsappCodeJoinRoute
  '/group/invite/whatsapp/$code/join-now': typeof GroupInviteWhatsappCodeJoinNowRoute
  '/group/invite/whatsapp/$code/': typeof GroupInviteWhatsappCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/how-reporting-works'
    | '/llms.txt'
    | '/moderation-policy'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/category/$slug'
    | '/data/addgroup'
    | '/group/addgroup'
    | '/group/find'
    | '/guides/how-to-avoid-whatsapp-scams'
    | '/guides/how-to-join-whatsapp-groups-safely'
    | '/guides/whatsapp-community-vs-group'
    | '/guides/whatsapp-group-admin-guidelines'
    | '/guides/whatsapp-groups-country-joining-guide'
    | '/guides/'
    | '/category/$slug/$group'
    | '/group/category/$slug'
    | '/group/country/$slug'
    | '/group/language/$slug'
    | '/group/invite/whatsapp/$code'
    | '/group/join/whatsapp/$code'
    | '/group/rules/whatsapp/$code'
    | '/group/invite/whatsapp/$code/join'
    | '/group/invite/whatsapp/$code/join-now'
    | '/group/invite/whatsapp/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/how-reporting-works'
    | '/llms.txt'
    | '/moderation-policy'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/category/$slug'
    | '/data/addgroup'
    | '/group/addgroup'
    | '/group/find'
    | '/guides/how-to-avoid-whatsapp-scams'
    | '/guides/how-to-join-whatsapp-groups-safely'
    | '/guides/whatsapp-community-vs-group'
    | '/guides/whatsapp-group-admin-guidelines'
    | '/guides/whatsapp-groups-country-joining-guide'
    | '/guides'
    | '/category/$slug/$group'
    | '/group/category/$slug'
    | '/group/country/$slug'
    | '/group/language/$slug'
    | '/group/join/whatsapp/$code'
    | '/group/rules/whatsapp/$code'
    | '/group/invite/whatsapp/$code/join'
    | '/group/invite/whatsapp/$code/join-now'
    | '/group/invite/whatsapp/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/how-reporting-works'
    | '/llms.txt'
    | '/moderation-policy'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/category/$slug'
    | '/data/addgroup'
    | '/group/addgroup'
    | '/group/find'
    | '/guides/how-to-avoid-whatsapp-scams'
    | '/guides/how-to-join-whatsapp-groups-safely'
    | '/guides/whatsapp-community-vs-group'
    | '/guides/whatsapp-group-admin-guidelines'
    | '/guides/whatsapp-groups-country-joining-guide'
    | '/guides/'
    | '/category/$slug_/$group'
    | '/group/category/$slug'
    | '/group/country/$slug'
    | '/group/language/$slug'
    | '/group/invite/whatsapp/$code'
    | '/group/join/whatsapp/$code'
    | '/group/rules/whatsapp/$code'
    | '/group/invite/whatsapp/$code/join'
    | '/group/invite/whatsapp/$code/join-now'
    | '/group/invite/whatsapp/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  HowReportingWorksRoute: typeof HowReportingWorksRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ModerationPolicyRoute: typeof ModerationPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DataAddgroupRoute: typeof DataAddgroupRoute
  GroupAddgroupRoute: typeof GroupAddgroupRoute
  GroupFindRoute: typeof GroupFindRoute
  GuidesHowToAvoidWhatsappScamsRoute: typeof GuidesHowToAvoidWhatsappScamsRoute
  GuidesHowToJoinWhatsappGroupsSafelyRoute: typeof GuidesHowToJoinWhatsappGroupsSafelyRoute
  GuidesWhatsappCommunityVsGroupRoute: typeof GuidesWhatsappCommunityVsGroupRoute
  GuidesWhatsappGroupAdminGuidelinesRoute: typeof GuidesWhatsappGroupAdminGuidelinesRoute
  GuidesWhatsappGroupsCountryJoiningGuideRoute: typeof GuidesWhatsappGroupsCountryJoiningGuideRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  CategorySlugGroupRoute: typeof CategorySlugGroupRoute
  GroupCategorySlugRoute: typeof GroupCategorySlugRoute
  GroupCountrySlugRoute: typeof GroupCountrySlugRoute
  GroupLanguageSlugRoute: typeof GroupLanguageSlugRoute
  GroupInviteWhatsappCodeRoute: typeof GroupInviteWhatsappCodeRouteWithChildren
  GroupJoinWhatsappCodeRoute: typeof GroupJoinWhatsappCodeRoute
  GroupRulesWhatsappCodeRoute: typeof GroupRulesWhatsappCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-reporting-works': {
      id: '/how-reporting-works'
      path: '/how-reporting-works'
      fullPath: '/how-reporting-works'
      preLoaderRoute: typeof HowReportingWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation-policy': {
      id: '/moderation-policy'
      path: '/moderation-policy'
      fullPath: '/moderation-policy'
      preLoaderRoute: typeof ModerationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/addgroup': {
      id: '/data/addgroup'
      path: '/data/addgroup'
      fullPath: '/data/addgroup'
      preLoaderRoute: typeof DataAddgroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/addgroup': {
      id: '/group/addgroup'
      path: '/group/addgroup'
      fullPath: '/group/addgroup'
      preLoaderRoute: typeof GroupAddgroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/find': {
      id: '/group/find'
      path: '/group/find'
      fullPath: '/group/find'
      preLoaderRoute: typeof GroupFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-avoid-whatsapp-scams': {
      id: '/guides/how-to-avoid-whatsapp-scams'
      path: '/guides/how-to-avoid-whatsapp-scams'
      fullPath: '/guides/how-to-avoid-whatsapp-scams'
      preLoaderRoute: typeof GuidesHowToAvoidWhatsappScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-join-whatsapp-groups-safely': {
      id: '/guides/how-to-join-whatsapp-groups-safely'
      path: '/guides/how-to-join-whatsapp-groups-safely'
      fullPath: '/guides/how-to-join-whatsapp-groups-safely'
      preLoaderRoute: typeof GuidesHowToJoinWhatsappGroupsSafelyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/whatsapp-community-vs-group': {
      id: '/guides/whatsapp-community-vs-group'
      path: '/guides/whatsapp-community-vs-group'
      fullPath: '/guides/whatsapp-community-vs-group'
      preLoaderRoute: typeof GuidesWhatsappCommunityVsGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/whatsapp-group-admin-guidelines': {
      id: '/guides/whatsapp-group-admin-guidelines'
      path: '/guides/whatsapp-group-admin-guidelines'
      fullPath: '/guides/whatsapp-group-admin-guidelines'
      preLoaderRoute: typeof GuidesWhatsappGroupAdminGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/whatsapp-groups-country-joining-guide': {
      id: '/guides/whatsapp-groups-country-joining-guide'
      path: '/guides/whatsapp-groups-country-joining-guide'
      fullPath: '/guides/whatsapp-groups-country-joining-guide'
      preLoaderRoute: typeof GuidesWhatsappGroupsCountryJoiningGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug_/$group': {
      id: '/category/$slug_/$group'
      path: '/category/$slug/$group'
      fullPath: '/category/$slug/$group'
      preLoaderRoute: typeof CategorySlugGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/category/$slug': {
      id: '/group/category/$slug'
      path: '/group/category/$slug'
      fullPath: '/group/category/$slug'
      preLoaderRoute: typeof GroupCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/country/$slug': {
      id: '/group/country/$slug'
      path: '/group/country/$slug'
      fullPath: '/group/country/$slug'
      preLoaderRoute: typeof GroupCountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/language/$slug': {
      id: '/group/language/$slug'
      path: '/group/language/$slug'
      fullPath: '/group/language/$slug'
      preLoaderRoute: typeof GroupLanguageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/invite/whatsapp/$code': {
      id: '/group/invite/whatsapp/$code'
      path: '/group/invite/whatsapp/$code'
      fullPath: '/group/invite/whatsapp/$code'
      preLoaderRoute: typeof GroupInviteWhatsappCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/join/whatsapp/$code': {
      id: '/group/join/whatsapp/$code'
      path: '/group/join/whatsapp/$code'
      fullPath: '/group/join/whatsapp/$code'
      preLoaderRoute: typeof GroupJoinWhatsappCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/rules/whatsapp/$code': {
      id: '/group/rules/whatsapp/$code'
      path: '/group/rules/whatsapp/$code'
      fullPath: '/group/rules/whatsapp/$code'
      preLoaderRoute: typeof GroupRulesWhatsappCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/invite/whatsapp/$code/': {
      id: '/group/invite/whatsapp/$code/'
      path: '/'
      fullPath: '/group/invite/whatsapp/$code/'
      preLoaderRoute: typeof GroupInviteWhatsappCodeIndexRouteImport
      parentRoute: typeof GroupInviteWhatsappCodeRoute
    }
    '/group/invite/whatsapp/$code/join': {
      id: '/group/invite/whatsapp/$code/join'
      path: '/join'
      fullPath: '/group/invite/whatsapp/$code/join'
      preLoaderRoute: typeof GroupInviteWhatsappCodeJoinRouteImport
      parentRoute: typeof GroupInviteWhatsappCodeRoute
    }
    '/group/invite/whatsapp/$code/join-now': {
      id: '/group/invite/whatsapp/$code/join-now'
      path: '/join-now'
      fullPath: '/group/invite/whatsapp/$code/join-now'
      preLoaderRoute: typeof GroupInviteWhatsappCodeJoinNowRouteImport
      parentRoute: typeof GroupInviteWhatsappCodeRoute
    }
  }
}

interface GroupInviteWhatsappCodeRouteChildren {
  GroupInviteWhatsappCodeJoinRoute: typeof GroupInviteWhatsappCodeJoinRoute
  GroupInviteWhatsappCodeJoinNowRoute: typeof GroupInviteWhatsappCodeJoinNowRoute
  GroupInviteWhatsappCodeIndexRoute: typeof GroupInviteWhatsappCodeIndexRoute
}

const GroupInviteWhatsappCodeRouteChildren: GroupInviteWhatsappCodeRouteChildren =
  {
    GroupInviteWhatsappCodeJoinRoute: GroupInviteWhatsappCodeJoinRoute,
    GroupInviteWhatsappCodeJoinNowRoute: GroupInviteWhatsappCodeJoinNowRoute,
    GroupInviteWhatsappCodeIndexRoute: GroupInviteWhatsappCodeIndexRoute,
  }

const GroupInviteWhatsappCodeRouteWithChildren =
  GroupInviteWhatsappCodeRoute._addFileChildren(
    GroupInviteWhatsappCodeRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  HowReportingWorksRoute: HowReportingWorksRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ModerationPolicyRoute: ModerationPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  DataAddgroupRoute: DataAddgroupRoute,
  GroupAddgroupRoute: GroupAddgroupRoute,
  GroupFindRoute: GroupFindRoute,
  GuidesHowToAvoidWhatsappScamsRoute: GuidesHowToAvoidWhatsappScamsRoute,
  GuidesHowToJoinWhatsappGroupsSafelyRoute:
    GuidesHowToJoinWhatsappGroupsSafelyRoute,
  GuidesWhatsappCommunityVsGroupRoute: GuidesWhatsappCommunityVsGroupRoute,
  GuidesWhatsappGroupAdminGuidelinesRoute:
    GuidesWhatsappGroupAdminGuidelinesRoute,
  GuidesWhatsappGroupsCountryJoiningGuideRoute:
    GuidesWhatsappGroupsCountryJoiningGuideRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  CategorySlugGroupRoute: CategorySlugGroupRoute,
  GroupCategorySlugRoute: GroupCategorySlugRoute,
  GroupCountrySlugRoute: GroupCountrySlugRoute,
  GroupLanguageSlugRoute: GroupLanguageSlugRoute,
  GroupInviteWhatsappCodeRoute: GroupInviteWhatsappCodeRouteWithChildren,
  GroupJoinWhatsappCodeRoute: GroupJoinWhatsappCodeRoute,
  GroupRulesWhatsappCodeRoute: GroupRulesWhatsappCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
